
version: '2'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    ports:
      - "6379:6379"
    expose:
      - "6379"
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - ~/apps/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root
#  myapplication:
 #   image: 'YOUR_APPLICATION_IMAGE'
  #  networks:
   #   - app-tier
